### ISSUE TITLE
Trying to run rgbmatrix

### ISSUE THREAD

**Issue by styoon07** [Puffball101961/matrixticker#27]
Hello Puffball101961
I want to add additional features to your code that I hope would benefit the trading/investing community.

I am having trouble trying to import rgbmatrix.
I was able to successfully import RGBMatrixEmulator.
Can you please guide me? I am new to all this.

**Comment by Puffball101961** [comment]
Hi!
If you are unable to import rgbmatrix it is because you first need to install the rgbmatrix library by Hzeller. Alternatively, you can use the python virtual environment that is present in the 'venv' folder in the root of the repository, which already has the rgbmatrix library installed.
